# Generated by Django 5.1.2 on 2024-12-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_photo_car_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='batalhao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='cia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='pelotao',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
