# Generated by Django 5.1.2 on 2024-12-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_batalhao_car_cia_car_pelotao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='batalhao',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='cia',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='pelotao',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
