# Generated by Django 5.1.2 on 2024-12-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_batalhao_alter_car_cia_alter_car_pelotao'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='prefixo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
