# Generated by Django 5.1.2 on 2024-12-10 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_batalhao_alter_car_batalhao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batalhao',
            old_name='nome',
            new_name='name',
        ),
    ]
