# Generated by Django 5.1.2 on 2024-12-12 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_alter_car_situacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='situacao',
        ),
    ]
